### PR TITLE
fix: faster LCP

### LINKED ISSUE #74: Homepage Lighthouse Score
Get LHS to 100.

One backup approach to get better perf from the image endpoints is to front them with the same domain name/cdn. But if there is anything else we can be doing to improve performance, that would be good to do.

main--firefly--adobecom.hlx.live

### PR DESCRIPTION
**Pull request by shsteimer**
fix: #74 

After: https://lcp--firefly--adobecom.hlx.live/

### CODE REVIEW

**Comment by shsteimer** [comment]
see https://thinktanked.org/tools/deep-psi/deep-psi.html?url1=https%3A%2F%2Fmain--firefly--adobecom.hlx.live%2F&url2=https%3A%2F%2Flcp--firefly--adobecom.hlx.live%2F for comparison. LCP average is lower, but with a wider range of outcomes.

File: aemedge/blocks/superhero/superhero.js [hunk 1]
```diff
@@ -165,12 +172,14 @@ export default async function decorate(block) {
     ingestAnalytics(analyticsEvent);
   });
   // Get the rest of the images
-  assetIds.forEach(async (assetId, i) => {
-    if (i !== 0) {
-      const picture = await createPitcureFromAssetId(assetId, false, false, 'high');
-      if (picture !== null) imageContainer.append(picture);
-    }
-  });
+  setTimeout(() => {
```
Comment (shsteimer) [inline aemedge/blocks/superhero/superhero.js:175]: not sure this makes a difference, but just ensuring the block decode returns before these start loading.

**Review by amol-anand — APPROVED** [review]
